### ISSUE TITLE
XMLNS Definitions not working on external libraries. 

### ISSUE THREAD

**Issue by jmacato** [cwensley/Portable.Xaml#105]
> This issue has been tested on Avalonia's latest nightly builds.
To repro, make a new Avalonia project, and add [AvaloniaEdit](https://www.nuget.org/packages/Avalonia.AvaloniaEdit/) package. Add the following namespace to MainWindow tag:
>```
>xmlns:ae="https://github.com/avaloniaui/avaloniaedit"
>```
>It should fail to find the type when you add the following control on MainWindow's main Grid:
>```
><ae:TextEditor/>
>```
https://github.com/AvaloniaUI/Avalonia/issues/1646

**Comment by dmetzgar** [comment]
I'm also seeing this. Here's the exception:
```
Result Message:	System.NotSupportedException : Current operation is valid only when the underlying type on a XamlType is known, but it is unknown for '{http://schemas.microsoft.com/netfx/2009/xaml/activities}Activity'
Result StackTrace:	
at Portable.Xaml.Schema.XamlTypeInvoker.ThrowIfUnknown()
   at Portable.Xaml.Schema.XamlTypeInvoker.CreateInstance(Object[] arguments)
   at Portable.Xaml.XamlObjectWriterInternal.InitializeObjectIfRequired(Boolean waitForParameters, Boolean required)
   at Portable.Xaml.XamlObjectWriterInternal.OnWriteStartObject()
   at Portable.Xaml.XamlWriterInternalBase.WriteStartObject(XamlType xamlType)
   at Portable.Xaml.XamlServices.Transform(XamlReader xamlReader, XamlWriter xamlWriter, Boolean closeWriter)
   at Portable.Xaml.XamlServices.Load(XamlReader xamlReader)
   at CoreWf.XamlIntegration.ActivityXamlServices.Load(XamlReader xamlReader, ActivityXamlServicesSettings settings) 
```

When I replace the URI in the namespace declaration `xmlns="http://schemas.microsoft.com/netfx/2009/xaml/activities"` with the CLR version `xmlns="clr-namespace:CoreWf;assembly=CoreWf"`, the `XamlServices.Load` will work.

**Comment by cwensley** [comment]
Hm, yeah this seems to be a problem when running on .NET Core, which I have seen before.  I think it's a problem with how Portable.Xaml tries to get the list of loaded assemblies.  Thanks for the details, guys!
